# Make sure you copy SSH keys to each machine for which you want to copy
[targets.production]
controller_path = "ft@<production-controller-host>:/home/ft/.local/share/footron/"
web_path = "footron@<production-web-host>:/var/www/footron.byu.edu/html/"
controller_api_url = "http://<production-controller-host>:8000/"

[targets.staging]
controller_path = "ft@<staging-host>:/home/ft/.local/share/footron/"
web_path = "ft@<staging-host>:/var/www/ft1s.cs.byu.edu/html/"
controller_api_url = "http://<staging-host>:8000/"
